version: '3.8'
services:
  nodo:
    build: .
    stdin_open: true
    tty: true
    ports:
      - "15000:5000"  # Host 15000 â†’ Container SIEMPRE 5000
    environment:
      - NODE_PORT=5000  # Puerto interno del contenedor
e